apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  podSubnet: "10.11.0.0/16" # --pod-network-cidr
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.10.1.1 # --apiserver-advertise-address
